id = "templ"
name = "Templ"
version = "0.0.2"
schema_version = 1
authors = ["Mehmet Akif Duba <mail@makifdb.com>"]
description = "Templ language support for Zed"
repository = "https://github.com/makifdb/zed-templ"

[language_servers.templ]
name = "Templ Language Server"
language = "Templ"

[grammars.templ]
repository = "https://github.com/vrischmann/tree-sitter-templ"
commit = "592faa3186ef857c92e4bd1c31d73c07a4a334db"
